services:
  - docker:dind

stages:
  - test
  - build
  - upload

before_script:
  - APP_VERSION=$(git describe --tags --always)
  - FQIN="${FQIP}:${APP_VERSION}"

.only: &only
  - tags

test:
  stage: test
  script:
    - docker build --target test --rm -t $FQIN .

build:
  stage: build
  only: *only
  script:
    - docker build --target build --rm -t $FQIN .
    - docker create --name builder $FQIN
    - docker cp builder:/app/dist ./dist
  artifacts:
    paths:
      - dist/*.whl

upload:
  stage: upload
  only: *only
  image: python:3.11
  script:
    - python -m pip install --upgrade pip
    - pip install twine
    - twine upload dist/*.whl --repository-url $PYPI_REPO_URL
