services:
  - docker:dind

stages:
  - build

before_script:
  - APP_VERSION=$(git describe --tags --always)
  - FQIN="${FQIP}:${APP_VERSION}"

.only: &only
  - tags

build:
  stage: build
  only: *only
  script:
    - docker build --target build -t $FQIN .
    - |
      docker run \
      -e TWINE_REPOSITORY_URL=${TWINE_REPOSITORY_URL} \
      -e TWINE_USERNAME=${TWINE_USERNAME} \
      -e TWINE_PASSWORD=${TWINE_PASSWORD} \
      $FQIN \
      twine upload 'dist/*.whl'
